name: Bug Report
description: Report a bug or problem with Tardis Refined
body:
  - type: markdown
    attributes:
      value: "*Please use the search functionality before reporting an issue to check if it has already been reported!*"
  - type: textarea
    attributes:
      label: Issue description
      description: A clear and concise description of the issue and expected outcome. Also add any relevant screenshots here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If there are specific steps that need to be taken to reproduce the issue list them here.
      placeholder: |
        1. Start by doing...
        2. Next do...
        3. See result described above
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using?
      options:
        - 1.20.2 (Latest)
        - 1.20.1
        - 1.19.2
    validations:
      required: true
  - type: dropdown
    id: platform-type
    attributes:
      label: Mod Loader Platform type
      description: What type of mod loader are you using?
      options:
        - Neoforge
        - Forge
        - Fabric
    validations:
      required: true
  - type: input
    attributes:
      label: Mod Loader version
      description: What version of mod loader are you using?
      placeholder: e.g. Forge Version 43.1.43, Fabric Loader Version 0.14.12
    validations:
      required: true
  - type: dropdown
    id: tardis_refined-version
    attributes:
      label: Tardis Refined version
      description: What version of Tardis Refined are you using?
      options:
        - v2.1.1
        - v2.1.0
        - v2.0.7
        - v2.0.6
        - v2.0.5
        - v2.0.4
        - v2.0.3
        - v2.0.2
        - v2.0.1
        - v2.0
        - v1.0
        - Pre-release v0.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other relevant versions
      description: If this issue is related to any other mods that have been installed alongside Tardis Refined, list the mod's name and version here.
  - type: textarea
    attributes:
      label: Mod List
      description: In order to check for compatibility issues, we require your mods list
  - type: checkboxes
    id: existing
    attributes:
      label: Please confirm that you have searched existing issues in the repo.
      options:
        - label: 'Yes, I have checked all open issues and am aware my issue will be closed if it is a duplicate of another'
  - type: checkboxes
    id: rendering
    attributes:
      label: Please confirm that if your issue is related to rendering, that you have tested without the following before testing; (Shaders, Optifine, Rubidium, embeddium, Sodium)
      options:
        - label: 'Yes, I have done testing without these mods before reported a rendering issue or my issue does not relate to rendering'
  - type: input
    attributes:
      label: "Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)"
      description: "You can use a website such as a [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc. and link it here. (Make sure that it isn't set to expire!)"
